fix:github action

diff --git a/.github/workflows/deploy-docker-ec2.yml b/.github/workflows/deploy-docker-ec2.yml
--- a/.github/workflows/deploy-docker-ec2.yml
+++ b/.github/workflows/deploy-docker-ec2.yml
@@ -87,24 +87,24 @@ on:
       - develop
 
 jobs:
-  build-and-push:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
+  # build-and-push:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v2
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-      # 使用Docker Compose構建Docker映像
-      - name: Build Docker images
-        run: |
-          docker-compose -f "${{ github.workspace }}/docker-compose.yml" build
-          docker-compose -f "${{ github.workspace }}/docker-compose.yml" push
-        working-directory: "${{ github.workspace }}" # 替換成你的項目路徑
+  #     # 使用Docker Compose構建Docker映像
+  #     - name: Build Docker images
+  #       run: |
+  #         docker-compose -f "${{ github.workspace }}/docker-compose.yml" build
+  #         docker-compose -f "${{ github.workspace }}/docker-compose.yml" push
+  #       working-directory: "${{ github.workspace }}" # 替換成你的項目路徑
 
       # - name: Upload config.env to EC2
       #   uses: appleboy/scp-action@v0.3.0
@@ -130,23 +130,40 @@ jobs:
       #       docker-compose down
       #       docker-compose pull
       #       docker-compose up -d
-      - name: SSH into EC2 and Deploy
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-        run: |
-          set -e
 
-          mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
+        - name: SSH into EC2 and Deploy
+          env:
+            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          run: |
+            set -e
 
-          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+            echo "Creating SSH directory and private key file..."
+            mkdir -p ~/.ssh
+            echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
+            chmod 600 ~/.ssh/id_rsa
 
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.SSH_HOST }} <<'ENDSSH'
-          cd my_docker_project
-          docker-compose down
-          docker-compose pull
-          docker-compose up -d
-          ENDSSH
-          
-          rm -f ~/.ssh/id_rsa
+            echo "Adding host to known_hosts..."
+            ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+
+            echo "Initiating SSH connection..."
+            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.SSH_HOST }} <<'ENDSSH'
+            set -e  # it will ensure that the script stops on the first error
+            echo "Navigating to project directory..."
+            if cd my_docker_project; then
+              echo "Directory exists. Continuing..."
+              docker-compose down
+              docker-compose pull
+              docker-compose up -d
+            else
+              echo "Directory does not exist. Exiting..."
+              exit 1
+            fi
+            ENDSSH
+
+            if [ $? -ne 0 ]; then
+              echo "SSH command failed"
+              exit 1
+            fi
+
+            echo "Removing private key..."
+            rm -f ~/.ssh/id_rsa
